In [1]:
import pandas as pd

In [7]:
a = [7, 9, 38, 24]
r = [202, 255, 854, 999]
g = [1, 10, 100, 1000]

In [8]:
suerte = pd.DataFrame({'a':a,'r':r,'g':g})

In [9]:
suerte

    a    r     g
0   7  202     1
1   9  255    10
2  38  854   100
3  24  999  1000

In [11]:
d = suerte['a']

In [12]:
type(d)

pandas.Series

In [13]:
e = list(d)

In [14]:
e

[7, 9, 38, 24]

In [15]:
a == e

True

In [18]:
suerte['row_mean'] = suerte.mean(axis=1)

In [19]:
suerte

    a    r     g    row_mean
0   7  202     1   70.000000
1   9  255    10   91.333333
2  38  854   100  330.666667
3  24  999  1000  674.333333

In [23]:
df = pd.read_csv('/work/Experimental Psycholinguistics 2026/Stroop-raw-over-the-years.csv')

In [24]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [30]:
df = df.drop(['Year'],axis=1)

In [31]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int
0             4.16        6.76          4.45         4.65
1             4.35        7.73          4.78         4.46
2             3.60        7.00          4.00         3.50
3             3.90        9.03          4.60         6.30
4             4.22        9.98          6.83         6.24
..             ...         ...           ...          ...
200           4.77       10.00          5.66         6.24
201           4.61       12.80          6.87         9.55
202           4.79       10.72          5.64         7.25
203           4.41        8.87          6.70         6.70
204           5.50        9.80          6.20        21.70

[205 rows x 4 columns]

AttributeError: 'DataFrame' object has no attribute 'Mean'