In [2]:
import pandas as pd

In [22]:
raw = pd.read_csv('/work/Psycholinguistics-2026/18-09 combined_data.csv')

In [4]:
#raw.head(20)

In [23]:
list(raw)

['participant_id',
 'component_num',
 'url',
 'meta',
 'sender',
 'sender_type',
 'sender_id',
 'ended_on',
 'duration',
 'time_run',
 'time_render',
 'time_show',
 'time_end',
 'time_commit',
 'timestamp',
 'time_switch',
 'response',
 'response_action',
 'prime',
 'target',
 'condition',
 'soa_condition',
 'congruence',
 'correct_response',
 'correctResponse',
 'correct']

In [24]:
cols = ['participant_id', 'sender', 'duration', 'response', 'condition', 'soa_condition','congruence', 'correct_response', 'correct', 'target']

In [25]:
df = raw[cols]

In [26]:
df = df[df['sender'] == 'target']

In [27]:
df

,participant_id,sender,duration,response,condition,soa_condition,congruence,correct_response,correct,target
13,51,target,843.38,n,practice,practice,practice,n,True,SHEEP
19,51,target,593.04,m,practice,practice,practice,m,True,BOAT
25,51,target,559.18,m,practice,practice,practice,m,True,HOUSE
31,51,target,653.76,n,practice,practice,practice,n,True,HORSE
40,51,target,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO
...,...,...,...,...,...,...,...,...,...,...
15606,69,target,699.20,m,Con_Synth,short,congruent,m,True,BELT
15612,69,target,580.20,n,Con_Nat,short,congruent,n,True,DAISY
15618,69,target,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED
15624,69,target,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY
15630,69,target,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL

In [28]:
sender_list = list(df['sender'])
set(sender_list)

{'target'}

In [29]:
df['sender'].unique()

<StringArray>
['target']
Length: 1, dtype: str

In [30]:
df = df[df['condition'] != 'practice']
df

,participant_id,sender,duration,response,condition,soa_condition,congruence,correct_response,correct,target
40,51,target,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO
47,51,target,640.66,n,Inc_Nat_Nat,long,incongruent,m,False,BULL
54,51,target,597.74,n,Inc_Synth_Nat,long,incongruent,n,True,GOAT
61,51,target,495.68,n,Con_Nat,long,congruent,n,True,PEAR
68,51,target,556.86,m,Inc_Nat_Synth,long,incongruent,m,True,MOTOR
...,...,...,...,...,...,...,...,...,...,...
15606,69,target,699.20,m,Con_Synth,short,congruent,m,True,BELT
15612,69,target,580.20,n,Con_Nat,short,congruent,n,True,DAISY
15618,69,target,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED
15624,69,target,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY
15630,69,target,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL

In [37]:
df = df.drop('sender', axis = 'columns', inplace=True)

KeyError: "['sender'] not found in axis"

In [32]:
df

,participant_id,sender,duration,response,condition,soa_condition,congruence,correct_response,correct
40,51,target,520.14,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,target,640.66,n,Inc_Nat_Nat,long,incongruent,m,False
54,51,target,597.74,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,target,495.68,n,Con_Nat,long,congruent,n,True
68,51,target,556.86,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...
15606,69,target,699.20,m,Con_Synth,short,congruent,m,True
15612,69,target,580.20,n,Con_Nat,short,congruent,n,True
15618,69,target,577.90,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,target,661.10,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,target,709.20,n,Inc_Nat_Nat,short,incongruent,n,True

In [17]:
df.loc[df['target'] == 'BULL', 'correct_response'] = 'n'
df

,participant_id,duration,response,condition,soa_condition,congruence,correct_response,correct,target
40,51,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO
47,51,640.66,n,Inc_Nat_Nat,long,incongruent,n,False,BULL
54,51,597.74,n,Inc_Synth_Nat,long,incongruent,n,True,GOAT
61,51,495.68,n,Con_Nat,long,congruent,n,True,PEAR
68,51,556.86,m,Inc_Nat_Synth,long,incongruent,m,True,MOTOR
...,...,...,...,...,...,...,...,...,...
15606,69,699.20,m,Con_Synth,short,congruent,m,True,BELT
15612,69,580.20,n,Con_Nat,short,congruent,n,True,DAISY
15618,69,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED
15624,69,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY
15630,69,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL

In [18]:
df['accuracy'] = df['response'] == df['correct_response']
df

,participant_id,duration,response,condition,soa_condition,congruence,correct_response,correct,target,accuracy
40,51,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO,True
47,51,640.66,n,Inc_Nat_Nat,long,incongruent,n,False,BULL,True
54,51,597.74,n,Inc_Synth_Nat,long,incongruent,n,True,GOAT,True
61,51,495.68,n,Con_Nat,long,congruent,n,True,PEAR,True
68,51,556.86,m,Inc_Nat_Synth,long,incongruent,m,True,MOTOR,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,m,Con_Synth,short,congruent,m,True,BELT,True
15612,69,580.20,n,Con_Nat,short,congruent,n,True,DAISY,True
15618,69,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED,True
15624,69,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY,True
15630,69,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL,True

In [1]:
df_grouped = df.groupby(['participant_id', 'soa_condition', 'congruence'])['duration'].mean().reset_index()

NameError: name 'df' is not defined

In [ ]:
df_grouped

In [98]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
ax = sns